app/controllers/menu_controllers.py
import sqlalchemy as sa

from app import db
from app.models import MenuItem, Order


def get_menu_items():
    query = sa.select(MenuItem)
    return db.session.scalars(query)


def all_menu_items_available(menu_items):
    for menu_item in menu_items:
        if not menu_item.is_available:
            return False
    return True


def _get_order_items(order):
    query = order.order_items.select()
    db.session.scalars(query).all()


class _Order:
    """wrapper around order to bind order items with it"""

    def __init__(self, order):
        self.order = order

    def __getattr__(self, name):
        return getattr(self.order, name)

    @property
    def order_items(self):
        query = self.order.order_items.select()
        return db.session.scalars(query).all()


def get_active_orders():
    """return orders with completed payment"""

    query = sa.select(Order).where(Order.status == "pending")
    for order in db.session.scalars(query):
        # the payment associated with the order
        payment = db.session.scalar(order.payment.select())
        if payment.get_status() == "completed":
            # yield only if the payment is completed
            yield _Order(order)


def set_menu_item_availability(menu_item_id, new_state):
    menu_item = db.session.get(MenuItem, menu_item_id)
    if not menu_item:
        raise Exception("menu item doesn't exist.")

    if menu_item.is_available == new_state:
        raise Exception(
            f"menu_item is already {'available' if new_state else 'unavailable'}"
        )

    menu_item.toggle_availability()
    db.session.commit()

app/views/user_views.py
import json

from flask import render_template, redirect, url_for, request, flash, Blueprint
from flask_login import current_user, logout_user

from app.forms import SignupForm, LoginForm
from app.controllers.menu_controllers import get_menu_items
from app.controllers.payment_controllers import get_checkout_url, resolve_payment
from app.controllers.auth_controllers import (
    login_response,
    signup_response,
    login_required,
)

users_blueprint = Blueprint("users", __name__)


@users_blueprint.route("/")
@users_blueprint.route("/home")
def home():
    return render_template("index.html")


@users_blueprint.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated and current_user.get_role() == "customer":
        return redirect(url_for("users.menu"))

    form = LoginForm()
    return login_response(form)


@users_blueprint.route("/logout")
@login_required("customer")
def logout():
    logout_user()
    return redirect(url_for("users.home"))


@users_blueprint.route("/signup", methods=["GET", "POST"])
def signup():
    if current_user.is_authenticated and current_user.get_role() == "customer":
        return redirect(url_for("users.menu"))
    form = SignupForm()
    return signup_response(form)


@users_blueprint.route("/menu")
@login_required("customer")
def menu():
    tx_ref = request.args.get("tx_ref")
    if tx_ref:
        try:
            result = resolve_payment(tx_ref)
            if result is True:
                # payment was successful
                flash(
                    "Your payment was processed successfully. your order has been queued.",
                    "success",
                )
            elif result is False:
                # payment has failed
                flash("There was an issue processing your payment.", "error")
            elif result is None:
                flash("Payment is pending, refresh this page to see updates.")
        except Exception as e:
            pass

    menu_items = get_menu_items()
    return render_template("menu/menu.html", menu_items=menu_items)


@users_blueprint.route("/order", methods=["POST"])
@login_required("customer")
def order():
    order_items = json.loads(request.form.get("order"))
    checkout_url = get_checkout_url(order_items)
    return redirect(checkout_url)


@users_blueprint.route("/order_history")
@login_required("customer")
def order_history():
    return render_template("placeholder.html")

app/templates/menu/menu.html
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   <link rel="icon" type="image/png" sizes="32x32"
      href=" {{url_for('static', filename='images/favicon.ico')}}" />

   <title>FOS</title>
   <link rel="stylesheet" href="{{url_for('static', filename='css/menu.css')}}" />
</head>

<body>
   <div class="app">
      <nav class="fixed-navbar">
         <div class="nav-left">
           <img src="{{url_for('static', filename='images/default-avatar.png')}}" alt="Avatar" class="avatar">
           <span class="username">{{current_user.username}}</span>
         </div>
         <div class="nav-right">
           <a href="{{url_for('users.order_history')}}">Order History</a>
           <a href="{{url_for('users.logout')}}">Logout</a>
         </div>
      </nav>
      <div class="app__container">
         <div class="app__container-products">
            <div class="app__header">
               <h1>Menu</h1>
               <button onclick="showCart()">
                  <img src="{{url_for('static', filename='images/menu/shopping-cart.png')}}" alt="cart" />
               </button>
            </div>
            <div class="app__container-products__menu">
               {% for product in menu_items %}
               <div class='product {{"" if product.is_available else "out-of-stock"}}'>
                  <div class='product__container-image'>
                     <picture>
                        <img src="{{url_for('static', filename='images/menu/')}}{{product.id}}.jpg" alt="{{product.name}}">
                     </picture>
                     {% if not product.is_available %}
                     <div class="out-of-stock-banner">Out Of Stock</div>
                     {% endif %}
                     <div class='product__actions'>
                        <button
                        id='{{product.id}}'
                        onclick='AddToCart(this, {{product.as_json_string() | safe}})' 
                        {{"" if product.is_available else "disabled"}}>
                           <img src=' {{url_for("static", filename="images/menu/icon-add-to-cart.svg")}}'>
                           <span>Add to Cart</span>
                        </button>
                        <div class='quantity'>
                           <div class='decrement' onclick='decrement({{product.as_json_string() | safe}}, this)'>
                              <img src='{{url_for("static", filename="images/menu/icon-decrement-quantity.svg")}}'>
                           </div>
                           <span>1</span>
                           <div class='increment' onclick='increment({{product.as_json_string() | safe}}, this)'>
                              <img src='{{url_for("static", filename="images/menu/icon-increment-quantity.svg")}}'>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class='product__container-content'>
                     <h2>{{product.name}}</h2>
                     <p>{{product.price}} ብር</p>
                  </div>
               </div>
               {% endfor %}
            </div>
         </div>
         <div class="cart__wrapper">
            <div class="app__container-order">
               <img src="{{url_for('static', filename='images/menu/icon-remove-item.svg')}}" class="remove-cart-icon"
                  onclick="hideCart()" />
               <h1>Your Cart (<span>0</span>)</h1>
               <div class="app__container-order__list"></div>
               <div class="app__container-order__total">
                  <span>Order Total</span>
                  <h2 class="total"></h2>
               </div>
               <div class="app__container-order__info"></div>
               <form action="order" method="POST">
                  <input type="textarea" name="order" id="order" hidden>
                  <button type="submit" class="app__container-order__btn">
                     Confirm Order
                  </button>
               </form>
            </div>
         </div>
      </div>
   </div>

    <!-- Modal Structure for showing flashed messages -->

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
         <div id="modal-overlay" class="modal-overlay show">
            <div class="modal">
                  <h2 id="modal-title" class="{{category}}">Payment Status</h2>
                  <p id="modal-message">{{message}}</p>
                  <button onclick="closeModal()">Close</button>
            </div>
         </div>    
      {% endfor %}
    {% endif %}
    {% endwith %}
   </div>
   <script src="{{url_for('static', filename='js/menu.js')}}"></script>
</body>

</html>